version: '3'
services:
  db:
    image: mongo
    restart: always
  backend:
    image: dart:2.19
    volumes:
      - ./backend:/backend/
    ports:
      - "3000:3000"
    command: bash -c "cd /backend && dart pub get && dart run bin/server.dart"
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend/build/web:/usr/share/nginx/html/
    ports:
      - "80:80"

